# Generated by Django 3.2.9 on 2021-11-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bugs',
            new_name='Bug',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
